### PR TITLE
Webpack build

### PR DESCRIPTION
**Pull request by makss**
Changes:
* Webpack
* AutoBuild/Repair `manifest.json`, if need. Data is taken from `/src/templates/manifest.json`(if exists) or `/package.json` or used default.

@philwareham please check the file `/dist/default_theme/default.css` there are [differences](https://github.com/textpattern/textpattern-default-theme/commit/d7170d9fffc57ff6e3266f19f0ea3ecdbc867750) associated with `autoprefixer`, but I do not know how critical they are.

### CODE REVIEW

**Comment by makss** [comment]
I found the cause of the differences css - an [updated version autoprefixer](https://github.com/textpattern/textpattern-default-theme/pull/104). I put an older version of the autoprefixer and got exactly the same css as in the branch master.

**Comment by philwareham** [comment]
Hi makss, thanks for this work!

I'm using the latest version of autoprefixer already aren't I? Maybe the autoprefixer in your Webpack version is not reading/respecting the `browserslist` rules  in `package.json`? Also I can't see autoprefixer listed as a dev dependency in your `package.json` file - does Webpack load that in a different way (I assumed PostCSS plugins such as Autoprefixer would still need to be installed via NPM?).

**Comment by makss** [comment]
Probably in the master branch you need to run the build.

**Comment by philwareham** [comment]
Ah, I've found the issue - because you are not specifying autoprefixer in NPM it's just installing the minimum version required by another plugin (in this case CSSnano) which is older (v6.7.7). That version didn't support the `browserlist` feature hence why it's using it's default settings.

Therefore you'll need to add the following into the dev dependencies to get it back to normal:

    "autoprefixer": "7.1.6",

**Comment by makss** [comment]
Fixed

**Comment by philwareham** [comment]
Lovely stuff. I need to dissect this now to see how it does what it does. 😀

**Pull request merged**
