### PR TITLE
Links don't have to be external

### PR DESCRIPTION
**Pull request by petecooper**
Internal links need love, too.

### CODE REVIEW

**Comment by philwareham** [comment]
Agreed, thanks Pete. I'll investigate whether middot needs any aria role on it, and amend if necessary.

**Comment by petecooper** [comment]
I used `&middot;` without any particular strong feeling. `&ndash` might work at a push, `&mdash` was too abrupt, and a simple figure dash might sidestep any aria role complications.

**Comment by philwareham** [comment]
That's semantically fine I think, it's a 'middle dot' logically separates two pieces of information. Looking through WordPress source code they use the same (without ARIA) so I'll leave it how you've done it.

**Comment by petecooper** [comment]
Great - thank you. Invoice is in the post, as usual.

For what it's worth, I really like how Hive is evolving. Thanks for all your work on this.

**Pull request merged**
